"""create farms table

Revision ID: 6c69710303a7
Revises: 
Create Date: 2026-06-06 13:46:34.291513
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c69710303a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farmer_name', sa.String(length=255), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('crop_type', sa.Enum('tea', 'maize', 'coffee', 'beans', 'vegetables', name='crop_type'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('farm_size_acres', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farmer_name', 'latitude', 'longitude', name='uq_farm_farmer_coords')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farms')
    # ### end Alembic commands ###