/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as FarmsRouteImport } from './routes/farms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmsIndexRouteImport } from './routes/farms.index'
import { Route as FarmsNewRouteImport } from './routes/farms.new'
import { Route as FarmsFarmIdRouteImport } from './routes/farms.$farmId'
import { Route as FarmsFarmIdEditRouteImport } from './routes/farms.$farmId.edit'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsRoute = FarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsIndexRoute = FarmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmsRoute,
} as any)
const FarmsNewRoute = FarmsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FarmsRoute,
} as any)
const FarmsFarmIdRoute = FarmsFarmIdRouteImport.update({
  id: '/$farmId',
  path: '/$farmId',
  getParentRoute: () => FarmsRoute,
} as any)
const FarmsFarmIdEditRoute = FarmsFarmIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => FarmsFarmIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/farms': typeof FarmsRouteWithChildren
  '/usage': typeof UsageRoute
  '/farms/$farmId': typeof FarmsFarmIdRouteWithChildren
  '/farms/new': typeof FarmsNewRoute
  '/farms/': typeof FarmsIndexRoute
  '/farms/$farmId/edit': typeof FarmsFarmIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/usage': typeof UsageRoute
  '/farms/$farmId': typeof FarmsFarmIdRouteWithChildren
  '/farms/new': typeof FarmsNewRoute
  '/farms': typeof FarmsIndexRoute
  '/farms/$farmId/edit': typeof FarmsFarmIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/farms': typeof FarmsRouteWithChildren
  '/usage': typeof UsageRoute
  '/farms/$farmId': typeof FarmsFarmIdRouteWithChildren
  '/farms/new': typeof FarmsNewRoute
  '/farms/': typeof FarmsIndexRoute
  '/farms/$farmId/edit': typeof FarmsFarmIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/farms'
    | '/usage'
    | '/farms/$farmId'
    | '/farms/new'
    | '/farms/'
    | '/farms/$farmId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/usage'
    | '/farms/$farmId'
    | '/farms/new'
    | '/farms'
    | '/farms/$farmId/edit'
  id:
    | '__root__'
    | '/'
    | '/farms'
    | '/usage'
    | '/farms/$farmId'
    | '/farms/new'
    | '/farms/'
    | '/farms/$farmId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FarmsRoute: typeof FarmsRouteWithChildren
  UsageRoute: typeof UsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms': {
      id: '/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof FarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/': {
      id: '/farms/'
      path: '/'
      fullPath: '/farms/'
      preLoaderRoute: typeof FarmsIndexRouteImport
      parentRoute: typeof FarmsRoute
    }
    '/farms/new': {
      id: '/farms/new'
      path: '/new'
      fullPath: '/farms/new'
      preLoaderRoute: typeof FarmsNewRouteImport
      parentRoute: typeof FarmsRoute
    }
    '/farms/$farmId': {
      id: '/farms/$farmId'
      path: '/$farmId'
      fullPath: '/farms/$farmId'
      preLoaderRoute: typeof FarmsFarmIdRouteImport
      parentRoute: typeof FarmsRoute
    }
    '/farms/$farmId/edit': {
      id: '/farms/$farmId/edit'
      path: '/edit'
      fullPath: '/farms/$farmId/edit'
      preLoaderRoute: typeof FarmsFarmIdEditRouteImport
      parentRoute: typeof FarmsFarmIdRoute
    }
  }
}

interface FarmsFarmIdRouteChildren {
  FarmsFarmIdEditRoute: typeof FarmsFarmIdEditRoute
}

const FarmsFarmIdRouteChildren: FarmsFarmIdRouteChildren = {
  FarmsFarmIdEditRoute: FarmsFarmIdEditRoute,
}

const FarmsFarmIdRouteWithChildren = FarmsFarmIdRoute._addFileChildren(
  FarmsFarmIdRouteChildren,
)

interface FarmsRouteChildren {
  FarmsFarmIdRoute: typeof FarmsFarmIdRouteWithChildren
  FarmsNewRoute: typeof FarmsNewRoute
  FarmsIndexRoute: typeof FarmsIndexRoute
}

const FarmsRouteChildren: FarmsRouteChildren = {
  FarmsFarmIdRoute: FarmsFarmIdRouteWithChildren,
  FarmsNewRoute: FarmsNewRoute,
  FarmsIndexRoute: FarmsIndexRoute,
}

const FarmsRouteWithChildren = FarmsRoute._addFileChildren(FarmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FarmsRoute: FarmsRouteWithChildren,
  UsageRoute: UsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
